#!/bin/sh

source /etc/pbs.conf

# Extend PATH so swig is available
PATH=~dtalcott/swig/bin:$PATH
# Point repo at sources used to build current pbs_python
repo=~dtalcott/work/drtoss
defs="-DNAS"

# Extract pieces needed to define pbs_conf structure

(
	grep "^#define.*MAXAUTHNAME" ${repo}/src/include/libauth.h
	sed -n -e '/struct pbs_config/,/extern struct pbs_config/p' \
		$repo/src/include/pbs_internal.h | \
	sed -e 's/psi_t/void/'
) > my_pbsconf.h

swig -python -I${repo}/src/include ${defs} ./pbs_ifl.i

t=$(pbs_python --version)
version=${t#pbs_version = }
pyinc=$(python3-config --includes)
gcc -g -O0 -Wall -Wno-unused-variable -fPIC -shared \
	-I ${repo}/src/include \
	$pyinc \
	-D PBS_VERSION='"'$version'"' \
	${defs} \
	-L ${PBS_EXEC}/lib \
	-lpbs \
	-Wl,-rpath=${PBS_EXEC}/lib \
	-o _pbs_ifl.so \
	./pbs_ifl_wrap.c

ldd _pbs_ifl.so
