.TH NAS_QSTAT 1 "2020-05-04" Local "OpenPBS contributions"
.SH NAME
.B nas_qstat
- display status of PBS jobs, queues, or servers

.SH SYNOPSIS
.B Displaying Job Status
.RS
.B nas_qstat
[-i|-r] [-G|-M] [-J] [-n] [-s] [-t] [-x] [-W option] [[<job ID> | <destination>] ...]
.sp
.RE
.B Displaying Queue Status
.RS
.B nas_qstat
-Q [<destination> ...]
.sp
.RE
.B Displaying Server Status
.RS
.B nas_qstat
-B [<server> ...]
.sp
.RE
.B Version Information
.br
.RS
.B nas_qstat
--version
.sp
.RE
.SH DESCRIPTION
The
.B nas_qstat
command displays the status of jobs, queues, or servers, writing
the status information to standard output.
.SH OPTIONS
.TP
.B -a
Precede job information section with information about the server and
compute resources.

.TP
.B -B
Display status for PBS server hosts listed on command line. If none specified,
display information for the local host's default PBS server.

.TP
.B -G
Display memory sizes in gigabytes, rather than megabytes.

.TP
.B -H
Selects only finished jobs or those moved to other PBS servers.

.TP
.B -J
Display status for job arrays, but not subjobs.

.TP
.B -M
Display memory sizes in 8 byte megawords.

.TP
.B -Q
Display status for PBS queues. Destination operands are queue names at the
default server. Queues at others servers can be specified as
.IR "queue_name@server" .

.TP
.BI -W " display_option"
Options affecting how statuses are displayed.
See
.B "\-W OPTIONS"
section.

.TP
.B -i
Selects only queued, held, or waiting jobs.

.TP
.B -n
List the nodes where a job is running on a separate line following the job
information.

.TP
.B -r
Selects only running, suspended, or exiting jobs.

.TP
.B -s
Include system comment about the job on a separate line following the job
information.

.TP
.B -t
Display status for jobs, job_arrays, and subjobs.

.TP
.BI -u " user"
Select only jobs from specified user.

.TP
.B -x
Include finished and moved jobs (if the server is configured to maintain
job history).

.TP
.BI --debug " option"
Debugging options for developers. See DEBUG OPTIONS section.
.SS -W OPTIONS
The
.B -W
argument accepts many options that change what information is displayed or
how it is displayed. Multiple options are specified using multiple
.B -W
instances.
Some of the options need quoting to protect them from the shell.

.TP
.BI fmt_ name = formatting_options
Apply specified formatting options to the field given by
.IR name .
Formatting options accumulate and the last one specified wins.
.sp
In the displayed output, each field occupies a column. Each column has three
parts. First is one or more rows giving the title for the column
(e.g., "User" or "Jobname").
Next is a row of dashes to separate the titles from the field values.
Last are the rows of values for the field.
The formatting options for the headers, the dashes, and the values can
be controlled individually.
.sp
Options are specified as a space-separated list of
.BI name: value
pairs. See
.BR EXAMPLES .
The option names are:
.RS

.TP
.B df:
(dash\ fill) The string to repeat to form the horizontal separator between
the title lines and the data lines (default '-').

.TP
.B dj:
(dash\ just) Justification to apply to separator fill. See
.B hj:
for values.

.TP
.B ds:
(dash\ separator) Character between this field and the next (default
.BR hs ).

.TP
.B dt:
(dash\ trunc) String to indicate truncation of field (default
.BR ht ).

.TP
.B hf:
(header\ fill) String to fill title text to width of column (default space).

.TP
.B hj:
(header\ just) Justification to apply to title text. Values are
 'l': left justified;
 'r': right justified;
 'c': centered;
 'lr': left justified first line, remaining right justified;
 'e': end justified, equivalent to left justified if text fits within
column width. If text needs to be truncated, the trucation will happen
in the middle and the ends will be retained.

.TP
.B hs:
(header\ separator) Character between this field and the next (default
space, unless
.B maxw:
== 0).

.TP
.B ht:
(header\ trunc) String to indication truncation of the field (default nothing).

.TP
.B maxw:
(max\ width) Maximum width of column.
If not set, nas_qstat picks a width that accommodates all values.

.TP
.B minw:
(min\ width) Minimum width of column.

.TP
.B rf:
(row\ fill) String to fill data values to width of column (default
.BR hf ).

.TP
.B rj:
(row\ just) Justification to apply to data values (default
.BR hj ).
See
.B hj for values.

.TP
.B rs:
(row\ separator) Character between this field and the next (default
.BR hs ).

.TP
.B rt:
(row\ trunc) String to indicate truncation of field (default
.BR ht ).

.TP
.B suppress:
Set to True to suppress column from output. This is different
from
.B o=-name
in that the latter removes the field everywhere, whereas the
former can be used to enable or disable the field on a
server by server basis.

.TP
.B title:
String to use as title for column.
.RE
.sp
Ex:
.B "-W fmt_jobname='maxw:20 hj:e ht:...'"
.sp
.RS
Notice that the settings for the dash and data rows default to the
settings for the header rows.
.RE
.sp

.TP
.BI fmta_ name = formatting options
Like
.BI fmt_ name
described above, except applied to the fields in the
.B -a
node output.

.TP
.BI condense_vnodes=host[,host...]
If the PBS server appears in the comma-separated list of hosts,
then nodes with multiple vnodes should be summarized in the
.B \-a output.
That is, when a vnode agrees with the
natural vnode in queue and vntype, and when its state is
similar to the natural vnode's state, then sum the vnode's
resources into the entry for the natural vnode. Otherwise,
the vnode appears by itself.
.sp
Instead of a host list, the values "True" or "False" (or "t"/"f") can be
used to enable/disable condensing for all servers.
.TP
.BI host[s]= host_pattern
Restrict reporting of jobs to those running on nodes whose names match the
regular expression given by
.IR host_pattern .
As a convenience, any commas (,) in the pattern are replaced by the
regular expression alternative indicator (|). Thus, "hosts=mercury,jupiter"
matches either of the the hosts "mercury" or "jupiter".
The pattern will often need to be quoted to protect it from the shell.
.br
This option also selects which hosts will be reported in the nodes section
of
.B
-a
output.

.TP
.B human
When time durations are displayed, convert durations over 48 hours to
days.

.TP
.B model
At NAS, include the node model type in the
.I info
field of the
.B -a
node status display.

.TP
.BI node_bin_total= nnn
When generating the node information at the beginning of the
.B -a
output,
if there are
.I nnn
or more nodes to display, then summarize similar nodes, rather than listing
them individually.
See also
.BR node_bin_size .

.TP
.BI node_bin_size= mmm
When the number of nodes selected for the
.B -a
output exceeds the value of
.BR node_bin_total ,
then collect similar nodes into groups and output a summary line for
each group of more than
.I mmm
similar nodes.
Otherwise, individually display the nodes in the group.
Nodes are "similar" when their info fields are identical.

.TP
.B node_comments
Include node comments in node "info" field of the
.B -a
output.

.TP
.B node_detail
Replace total CPU count column in
.B -a
output with columns giving used and free CPUs and used and free memory for the nodes.

.TP
.BR noheader " or " -h
Suppresses column identifier and dash lines from status output.
Useful when output is passed to another program for analysis.

.TP
.BI o= [+-]field_list
Change which fields are displayed.
The
.I
field_list
is a comma-separated list of field names to display.
If the list is prefixed with '-', the given fields are removed from the display list.
If the list is prefixed with '+', the given fields are appended to the display list.
Specifying
.RB ' o=? '
requests nas_qstat to list the currently known fields and then exit.
The known fields can be changed by the site administrator or by the user.
The current list is acct, aoe, cnt, cpct, cput, ctime, eff, elapwallt, eligtime, eligwait, estend, eststart, exitstatus, group, jobid, jobname, lifetime, maxwallt, memory, minwallt, mission, model, nds, place, pmem, pri, qtime, queue, rank0, reqid, reqmem, remwallt, reqdwallt, runs, s, sessid, seqno, ss, stime, tsk, user, vmem.

If the attribute or resource you are interested in is not in the known
field list, you request it by using a field name of 'A_xyz', 'RL_xyz',
or 'RU_xyz'. The 'A_' prefix indicates a job attribute; 'RL_' is for
a quantity from the job 'Resource_List' attribute; and 'RU_' refers
to 'resources_used' by running or completed jobs.
The
.I 'xyz'
portion of the field name must be typed exactly as it appears
in qstat -f output.

So, for example, if you want to include the Rerunable attribute for jobs,
you could use
.RE 1
.in 0
.EX

$ nas_qstat -W o=+A_Rerunable
                                              Req'd    Elap
JobID         User     Queue Jobname CPUs Nds wallt S wallt Eff Rerunable
------------- -------- ----- ------- ---- --- ----- - ----- --- ---------
12479.server2 dtalcott workq STDIN      1   1    -- H 00:00  -- True

.EE
.RS
If you want to see how much walltime was used, the following works:
.RE 1
.in 0
.EX

$ nas_qstat -x -W o=+RU_walltime
                                              Req'd    Elap
JobID         User     Queue Jobname CPUs Nds wallt S wallt Eff walltime
------------- -------- ----- ------- ---- --- ----- - ----- --- --------
12480.server2 dtalcott workq STDIN      2   1 01:00 F 00:01  0% 00:01:05

.EE
.RS
If you want to change how these fields are formatted, you can use the
usual -W fmt_name= method, where the field name includes the prefix. E.g.,
.B "-W fmt_A_Rerunable=maxw:5".
.TP
.BI oa= [+-]field_list
Like
.B o=
except that it applies to the fields in the
.B -a
output.
The current list of known fields is host, cpus, cused, cfree, gpus, gused, gfree, mem, mused, mfree, state, tasks, jobs, ninfo.

As with
.B o=
you can add to this list using special names for the fields. In this case, 'A_xyz', 'RA_xyz', or 'RI_xyz'. The 'A_' prefix selects a node attribute; 'RA_'
selects a resources_available quantity; and 'RI_' selects resources_assigned (in use).

.SH EXIT STATUS
Normally returns 0. Returns 1 on errors (e.g., nonexistent queue or jobid).

.SH ENVIRONMENT

.TP
.B HOME
Used to locate user's
.I .qstat_userexits
file.
If not set, the password database is consulted for the user's home directory.

.TP
.B PBS_DEFAULT
Specifies default PBS server host. If not set, the host's PBS configuration
file is consulted (usually
.IR /etc/pbs.conf ).

.SH FILES
.TP
PBS_EXEC/lib/site/qstat_userexits
Administrator provided python code to provide default values and
userexits. See
.B USEREXITS
section.
.TP
PBS_EXEC/bin/pbs_python
Python interpreter that runs
.BR nas_qstat .
.TP
$HOME/.qstat_userexits
User supplied python code to provide default values and userexits.
See
.B USEREXITS
section.

.SH USEREXITS
.B nas_qstat
invokes administrator- or user-supplied routines at specific
points during its execution.
These routines are defined by the site administrator from
a file at PBS_HOME/lib/site/qstat_userexits and by the user
from a file at $HOME/.qstat_userexits.
These routines are used to modify default settings, to
supply default
.B -W
options, or to otherwise customize
.B nas_qstat
output.

See the nas_qstat_userexits man page for more information.

See the EXAMPLE USEREXITS section for examples.
.SH EXAMPLES
.sp
Show running jobs.
.sp
.EX
\fBnas_qstat -r\fP
                                                 Req'd    Elap
JobID      User     Queue Jobname        TSK Nds wallt S wallt Eff
---------- -------- ----- -------------- --- --- ----- - ----- ---
38.server2 dtalcott workq longish_name_5   2   2 00:33 R 00:20 50%
.EE
.sp
Same, but include remaining walltime.
.sp
.EX
\fBnas_qstat -r -W o=+remwallt\fP
                                                 Req'd    Elap       Rem
JobID      User     Queue Jobname        TSK Nds wallt S wallt Eff wallt
---------- -------- ----- -------------- --- --- ----- - ----- --- -----
38.server2 dtalcott workq longish_name_5   2   2 00:33 R 00:24 50% 00:09
.EE
.sp
Show running jobs, but limit the Jobname field to 10 characters. Long
jobnames are truncated to a single "*" in the middle, keeping some
characters from each end.
.sp
.EX
\fBnas_qstat -r -W fmt_jobname='maxw:10 hj:e ht:*'\fP
                                             Req'd    Elap
JobID      User     Queue Jobname    TSK Nds wallt S wallt Eff
---------- -------- ----- ---------- --- --- ----- - ----- ---
39.server2 dtalcott workq long*ame_5   2   2 00:33 R 00:26 49%
.EE
.sp
Show waiting jobs along with summary of node status.
.sp
.EX
\fBnas_qstat -a -i\fP
server2:     Fri May  7 16:10:01 2021
 Server reports 4 jobs total (T:0 Q:2 H:1 W:0 R:1 E:0 B:0)

  Host  CPUs Tasks Jobs Info
  ----- ---- ----- ---- ------
  node4    1     0    0
  node5    0     0    0
  node6    0     0    0
  node7    0     0    0
  node3    2     2    1 in-use
                                          Req'd     Elap
JobID      User     Queue Jobname TSK Nds wallt S  wallt Eff
---------- -------- ----- ------- --- --- ----- - ------ ---
21.server2 dtalcott playq STDIN     1   1 00:33 Q 365:35  --
22.server2 dtalcott playq STDIN     1   1 00:33 Q 265:26  --
8.server2  dtalcott playq STDIN     1   1 00:03 H  00:00  --
.EE
.sp
Same, but summarize similar nodes (by setting the summarizing threshold low).
.sp
.EX
\fBnas_qstat -a -i -W node_bin_total=2\fP
server2:     Fri May  7 16:14:32 2021
 Server reports 4 jobs total (T:0 Q:2 H:1 W:0 R:1 E:0 B:0)

  Host     CPUs Tasks Jobs Info
  -------- ---- ----- ---- ------
   4 hosts    1     0    0
  node3       2     2    1 in-use
                                          Req'd     Elap
JobID      User     Queue Jobname TSK Nds wallt S  wallt Eff
---------- -------- ----- ------- --- --- ----- - ------ ---
21.server2 dtalcott playq STDIN     1   1 00:33 Q 365:40  --
22.server2 dtalcott playq STDIN     1   1 00:33 Q 265:30  --
8.server2  dtalcott playq STDIN     1   1 00:03 H  00:00  --
.EE
.SH EXAMPLE USEREXITS
This example shows a
.I qstat_userexits
file that a site might install in
.I PBS_EXEC/lib/site
to enable NAS options,
and make
.B node_detail
and
.B model
.B -W
options default.
.sp
.EX
# Enable NAS-specific features
globals()['gNAS'] = True

# Possibly do different things based on whether we are statusing hosts,
# queues, or jobs
if args.B:
    pass
elif args.Q:
    pass
else:
    # We add ngpus to default field list, if not already there
    if 'gpus' not in default_fields:
        # Add it after cpus field or at end
        try:
            t = default_fields.index('cpus')
        except:
            t = len(default_fields) - 1
        default_fields.insert(t+1, 'gpus')

    # Set up routine to set default -W values
    def site_post_opts(gbl, lcl):
        default_W = lcl['default_W']
        default_W.extend(['node_detail', 'model'])

    userexit_post_opts = stack_userexit(userexit_post_opts, site_post_opts)

    # Set up routine to tweak outputs based on server
    def site_set_server(g, lcl):
        server_name = lcl['current_server'].split('.')[0]
        cfg = lcl['cfg']
        svr_hdr = lcl.get('in_server_header', False)
        supgpu = server_name not in ['pbspl4']
        if svr_hdr:
            # Enable/disable all GPU fields in -a node output
            # If node_detail is selected on a GPU server, we
            # want to enable GPUs used and free. Otherwise, just
            # the GPUs field.
            node_detail = lcl.get('node_detail', False)
            cfg.change_fieldspec('gpus', suppress=supgpu or node_detail)
            cfg.change_fieldspec('gused', suppress=supgpu or not node_detail)
            cfg.change_fieldspec('gfree', suppress=supgpu or not node_detail)
        else:
            # Enable/disable job GPU column
            cfg.change_fieldspec('gpus', suppress=supgpu)

    userexit_set_server = stack_userexit(userexit_set_server, site_set_server)

.EE
.PP
The next example shows what a user might put in their
.I $HOME/.qstat_userexits
file.
This example limits the jobname field to 20 characters and uses "..."
to indicate parts of the name have been elided.
It also turns on the
.B "-W human"
option.
The
.B set_server
portion of the code limits the node info of the
.B -a
output to 30 characters, when running on a
particular host.

.EX
if args.B:
    pass
elif args.Q:
    pass
else:
    def my_post(gbl, lcl):
        default_W = lcl['default_W']
        # Keep jobname field reasonable
        default_W.extend(['fmt_jobname=maxw:20 hj:e rt:...'])
        # Use human readable durations
        default_W.extend(['human'])

    userexit_post_opts = stack_userexit(userexit_post_opts, my_post)

    def my_server(g, lcl):
        svr_hdr = lcl.get('in_server_header', False)
        server_name = lcl['current_server'].split('.')[0]
        if svr_hdr and server_name in ['pbspl4']:
            cfg = lcl['cfg']
            cfg.change_fieldspec('ninfo', maxw=30)

    userexit_set_server = stack_userexit(userexit_set_server, my_server)

.EE
.SH DEBUGGING OPTIONS
The
.B --debug
command line option is used by developers. As such, it is subject to
change.
Currently recognized options include:
.TP
\fBfake_\fIstat\fP_\fIhost\fP=\fIpath\fP
.B nas_qstat
normally queries PBS servers for information. However,
during development, it is useful to have a constant set of data to
work with, or data from servers that are not available to the
developers.
So, nas_qstat supports supplying data from text files instead of
from a server. The name of the debug option gives the pbs_statxxx
call to be faked and for which server.
.RS
.TP
.BI fake_jobs_ host
Supplies the file with
.B "qstat\ -f"
information for server
.IR host .
.TP
.BI fake_server_ host
Supplies the file with
.B "qstat\ -Bf"
information for server
.IR host .
.TP
.BI fake_vnodes_ host
Supplies the file with
.B "pbsnodes\ -av"
information for server
.IR host .
.TP
.BI fake_resvs_ host
Supplies the file with
.B "pbs_rstat\ -f"
information for server
.IR host .
.RE
Thus,
.B "--debug=fake_jobs_pbspl4=faked_jobs.txt"
says to read jobs status information for host pbspl4 from the file faked_jobs.txt.
.sp
.SH SEE ALSO
nas_qstat_userexits(3)
